### ISSUE TITLE
error message "Number.add: Parameter 'left' is required" after clicking compute restoration map

### ISSUE THREAD

**Issue by abczefg** [openforis/sepal-doc#100]
I built up this recipe (attached), and at the result map panel, after clicking "compute restoration map", I got this error message: Number.add: Parameter 'left' is required.
Then I tried to change the AoI and constraints, but still got the same error. 

<img width="641" alt="Screenshot 2021-12-06 at 20 09 07" src="https://user-images.githubusercontent.com/71498789/144860497-7c8e29c2-3153-4c50-b4bd-9e28e054bb7c.png">

[recipe_2021-12-06-test.txt](https://github.com/openforis/sepal-doc/files/7661220/recipe_2021-12-06-test.txt)

**Comment by 12rambau** [comment]
This issue is related to the se.plan app, I'll move it to the appropriate repository
