### ISSUE TITLE
Appui pour l'utilisation de l'application stratefied area estimator dans SEPAL

### ISSUE THREAD

**Issue by yelemou22** [openforis/sepal-doc#117]
Bonjour 
j'aimerais savoir si pour activer l'application Stratified area estimator - Design on a besoin d'activer une instance particulière ?.
Depuis 2 semaines j'essaie de l'ouvrir, mais je n'y arrive pas.

**Comment by 12rambau** [comment]
C'est très curieux. Normalement l'application ne nécessite pas d'instance particulières. Je viens de tester sur monordinateur avec un t2 et l'application a démarré sans difficultés après 1-2 min. 

pourriez-vous ajouter des détails pour que je puisse vous aider (screenshot, instance, navigateur....) ?

**Comment by lecrabe** [comment]
Bonjour. Le problème a été reglé sur le forum d'OpenForis. C'est lié à l'initialisation de R dans SEPAL. Pour les comptes qui n ont jamais utilisé R, les modules dans Shiny peuvent avoir un blocage car le dossier .R/ n'existe pas et le programme ne sait pas où installer les librairies potentielles.
Démarrer rstudio a vide permet de configurer tout cela. Ce n'est pas un problème d'instance donc
