### ISSUE TITLE
Manage multiple module tag

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal-doc#134]
In the current implementation of the module section, modules are ordered by tag. We are moving towards multiple tags per modules so we need to think about a new way to order them in the documentation. 

A way that stay compatible with both the html and the pdf output. 

ref: https://github.com/openforis/sepal/issues/168#issuecomment-1026070424

**Comment by yfinegold** [comment]
we could assign primary and secondary tags to modules

**Comment by 12rambau** [comment]
potential solution : 

create a stag page with all the tags and application (as a table for example). 
Every tag is shown as a link at the begining of each application documentation (with a link to the tag line in the tag page)
