### ISSUE TITLE
Extra equal signs in math and non-math text

### ISSUE THREAD

**Issue by i-m-amit** [openforis/sepal-doc#286]
There are extra equal signs in math and non-math. Examples
<img width="698" alt="image" src="https://user-images.githubusercontent.com/12950330/219716303-e8475f60-3c76-46f2-8b05-672db024de69.png">

<img width="698" alt="image" src="https://user-images.githubusercontent.com/12950330/219716479-4ccf29d3-1c3f-4029-a573-3fdf8168b992.png">

**Comment by 12rambau** [comment]
that is super weird and new! I need to check the python theme I think that's a version issue from mathjax.

thanks for reporting!
