### ISSUE TITLE
Could not import extension sphinxcontrib

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal-doc#30]
By following the [contribute documentation](https://docs.sepal.io/en/latest/team/contribute.html), I've found an error when executing the `make html` bash command, do you know what could have happened?.

```bash
Could not import extension sphinxcontrib.spelling (exception: The 'enchant' C library was not found and maybe needs to be installed.
See  https://pyenchant.github.io/pyenchant/install.html
for details
)
Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2

```

**Comment by 12rambau** [comment]
The enchant C lib is installed by default on RDT servers you need to install it on your machine as well, tell me if this is sufficient and I'll add it to the requirements:
```
pip install pyenchant
```

**Comment by ingdanielguerrero** [comment]
I've installed `pyenchant==3.2.0`, but seems like is not working, below the image error.

![image](https://user-images.githubusercontent.com/12363250/117982877-ba4ac400-b336-11eb-8b63-a51f4775b131.png)

**Comment by 12rambau** [comment]
Ok so according to the lib documentation installing the python Package is not sufficient you also need to install the C lib. This easy on you local computer but more complex on sepal. I'll open a PR to add the lib to the build

**Comment by 12rambau** [comment]
The lib is now part of SEPAL standard build. Reopen if it's still not working
