### ISSUE TITLE
build fails on schedule

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal-doc#386]
I think the build is failing because I've protected the main branch, so it can't be edited without a PR.
git-auto-commit-action@v4 detects new `.po` files and tries to commit directly to main (from where it's called in readthedocs?), it trhows an exception and the build fails.

perhaps we can commit those changes to a different branch...

**Comment by 12rambau** [comment]
the advantage of the self commit was to avoid to force you to merge the branch every day, but that's weird because normally it's my profile that is associated to it so I should have all the writes to overwrite any limitation as I'm owner of the repository. I'll have a look this WE (it's bugging me as it appeared continuously in my dashboard.

**Comment by dfguerrerom** [comment]
The main branch is protected, so new commits have to be done on a non-protected branch and submitted through a PR, does that applies to the owner as well?
anyways, if there are no changes to the documentation, there are no new files to commit and it won't create a commit, right?

**Comment by 12rambau** [comment]
> does that applies to the owner as well?

Normally creator of the repository have special status and can bypass everything 

> anyways, if there are no changes to the documentation, there are no new files to commit and it won't create a commit, right?

exactly

**Comment by 12rambau** [comment]
let's see what happen tomorrow but I thin this is now solved

**Comment by dfguerrerom** [comment]
an additional problem here is that `crowdin` and the build of `sphinx gettext` are in conflict, one removes the break lines of the `.po` files and the other creates the `.po` files with breaking lines, every time something changes, both job fails and modify everything.

**Comment by 12rambau** [comment]
That was a known bug from the start, I search everywhere how to remove linting/header from the gettext files and found nothing. My 2 cents, do we care ? as the PR are squash merged, it will have very little to no impact.

**Comment by 12rambau** [comment]
build are back on track: https://github.com/openforis/sepal-doc/actions/runs/5862254296

I'm closing this issue.
