### ISSUE TITLE
Review module's documentation

### ISSUE THREAD

**Issue by dfguerrerom** [openforis/sepal-doc#398]
This is just to keep track of all the documentation of the modules that need to be reviewed.

- [x] alert_module: https://github.com/sepal-contrib/alert_module/blob/release/doc/en.rst
- [x] alos_mosaics: https://github.com/sepal-contrib/alos_mosaics/blob/release/doc/en.rst
- [x] bfast_explorer: https://github.com/12rambau/bfast-explorer/blob/master/md/tutorial.rst
- [x] bfast_gpu: https://github.com/sepal-contrib/bfast_gpu/blob/release/doc/en.rst
- [x] bfast_r: https://github.com/12rambau/bfastspatial/blob/master/www/tutorial/tutorial.rst
- [x] clip-time-series: https://github.com/sepal-contrib/clip-time-series/blob/release/doc/en.rst
- [x] coverage_analysis: https://github.com/sepal-contrib/coverage_analysis/blob/release/doc/en.rst
- [x] damage_proxy_map: https://github.com/sepal-contrib/damage_proxy_maps/blob/release/doc/en.rst
- [x] fcdm: https://github.com/sepal-contrib/fcdm/blob/release/doc/en.rst
- [x] gfc_wrapper_python: https://github.com/sepal-contrib/gfc_wrapper_python/blob/release/doc/en.rst
- [x] gwb: https://github.com/sepal-contrib/gwb/blob/release/doc/en.rst
- [x] vector_manager: https://github.com/sepal-contrib/vector_manager/blob/release/doc/en.rst
- [x] planet_order: https://github.com/sepal-contrib/planet-order/blob/release/doc/en.rst
- [ ] sae_analysis: https://github.com/openforis/accuracy-assessment/blob/master/aa_analysis/doc.rst
- [x] sdg_indicator: https://github.com/sepal-contrib/sdg_15.3.1/blob/release/doc/en.rst
- [x] #399
- [x] sepal_mgci: https://github.com/sepal-contrib/sepal_mgci/blob/release/doc/en.rst
- [x] sepal_pysmm: https://github.com/sepal-contrib/sepal_pysmm/blob/release/doc/en.rst
- [x] seplan: https://github.com/sepal-contrib/se.plan/blob/release/doc/en.rst
- [x] smfm_biota: https://github.com/sepal-contrib/sepal_smfm_biota/blob/release/doc/en.rst
- [ ] zonal-analysis: https://github.com/sepal-contrib/zonal-analysis/blob/release/doc/en.rst
- [x] gee-source: https://github.com/sepal-contrib/gee_source/blob/release/doc/en.rst
- [x] weplan: https://github.com/sepal-contrib/weplan/blob/release/doc/en.rst
- [x] basin-river: https://github.com/sepal-contrib/basin-rivers/blob/blob/master/doc/en.rst

**Comment by dfguerrerom** [comment]
I have updated the most of the modules in their main branch in the origin with the files edited on https://github.com/openforis/sepal-doc/pull/406 and https://github.com/openforis/sepal-doc/pull/396.
I still need to reconciliate all `main` and `release` branches in the origin because not all modules documentation is cloned on their default branch, some of them uses release.

- [ ] reconciliate branches

**Comment by dfguerrerom** [comment]
I have re conciliated the most of the branches (checks from first post are up-to-date), there are still some others that:

have not been reviewed

- [ ] zonal-analysis: https://github.com/sepal-contrib/zonal-analysis/blob/release/doc/en.rst
- [ ] sae_analysis: https://github.com/openforis/accuracy-assessment/blob/master/aa_analysis/doc.rst

And others that we should transfer the authority to `sepal-contrib` in order to make them easier to support.

- [ ] bfast_explorer: https://github.com/12rambau/bfast-explorer/blob/master/md/tutorial.rst
- [ ] bfast_r: https://github.com/12rambau/bfastspatial/blob/master/www/tutorial/tutorial.rst

At the beginning I thought it was easier to just fork them using `sepal-contrib` and then just change the link from within SEPAL, but now I think is better to transfer the authority to avoid broken links if we remove the openforis original one after the fork here.

For the latest, we can find the last version on this PR https://github.com/openforis/sepal-doc/pull/396/files#diff-0f41daf8715eeb150b1ccc510089f15e24f02940d80434496fe03b831c2b67e8.

**Comment by 12rambau** [comment]
for the 2 that lives in my own repository do you want me to transfer them ?

**Comment by dfguerrerom** [comment]
> for the 2 that lives in my own repository do you want me to transfer them ? 
> 
> 

Humm I think it's better to transfer authority from the ones that are in openforis, if Im not wrong, you forked them because you wanted to update their documentation and your prs there were not merged, so you forked to create and link the documentation... Right?
Instead of having two repos, I'd like to transfer the authority from the originals and merge your doc commits on them and remove any other reference in openforis.

**Comment by 12rambau** [comment]
for bfastspatial yes (I should have merged them a long time ago) but for bfast-explorer it's not coming from openforis but the original app

**Comment by dfguerrerom** [comment]
We have transferred the ownership from `bfastspatial` and `bfast-explorer`
- [ ] Merged the documentation of `bfastspatial` with https://github.com/sepal-contrib/bfastspatial/pull/2
- [ ] Merged the documentation of `bfast-explorer` with https://github.com/sepal-contrib/bfast-explorer/pull/3
- [ ] Use sepal-contrib bfast spatial documentation link https://github.com/openforis/sepal-doc/pull/409
